import { useThemedStyles } from "@/hooks/useTheme";
import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { deleteMedication, listMedications, saveMedication } from '@/database/repositories/medicationRepository';
import { getPatient } from '@/database/repositories/patientRepository';
import type { Medication, Patient } from '@/types/health';

export default function MedicationsScreen(){
  const s = useThemedStyles(baseStyles);
 const {patientId:rawId}=useLocalSearchParams<{patientId:string}>();const patientId=Number(rawId);const db=useSQLiteContext();
 const [patient,setPatient]=useState<Patient|null>(null);const[items,setItems]=useState<Medication[]>([]);const[id,setId]=useState<number>();
 const[name,setName]=useState('');const[dosage,setDosage]=useState('');const[frequency,setFrequency]=useState('');const[start,setStart]=useState('');const[end,setEnd]=useState('');const[status,setStatus]=useState<'active'|'stopped'>('active');const[sideEffects,setSideEffects]=useState('');const[notes,setNotes]=useState('');
 const load=useCallback(async()=>{setPatient(await getPatient(db,patientId));setItems(await listMedications(db,patientId));},[db,patientId]);useFocusEffect(useCallback(()=>{load();},[load]));
 function reset(){setId(undefined);setName('');setDosage('');setFrequency('');setStart('');setEnd('');setStatus('active');setSideEffects('');setNotes('');}
 function edit(x:Medication){setId(x.id);setName(x.name);setDosage(x.dosage??'');setFrequency(x.frequency??'');setStart(x.start_date??'');setEnd(x.end_date??'');setStatus(x.status);setSideEffects(x.side_effects??'');setNotes(x.notes??'');}
 async function save(){if(!name.trim())return Alert.alert('Thiếu tên thuốc','Hãy nhập tên thuốc.');await saveMedication(db,{id,patientId,name,dosage,frequency,startDate:start,endDate:end,status,sideEffects,notes});reset();await load();}
 function remove(x:Medication){Alert.alert('Xóa thuốc?',x.name,[{text:'Hủy',style:'cancel'},{text:'Xóa',style:'destructive',onPress:async()=>{await deleteMedication(db,x.id);if(id===x.id)reset();await load();}}]);}
 return <ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><View style={s.hero}><Text style={s.overline}>MEDICATION TRACKER</Text><Text style={s.heroTitle}>{patient?.name??'Thuốc đang dùng'}</Text><Text style={s.heroText}>Theo dõi liều, lịch dùng, thời gian điều trị và tác dụng phụ.</Text></View>
 <Text style={s.heading}>{id?'Chỉnh sửa thuốc':'Thêm thuốc'}</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Tên thuốc *"/><View style={s.row}><TextInput style={[s.input,s.half]} value={dosage} onChangeText={setDosage} placeholder="Liều dùng"/><TextInput style={[s.input,s.half]} value={frequency} onChangeText={setFrequency} placeholder="Lịch uống"/></View><View style={s.row}><TextInput style={[s.input,s.half]} value={start} onChangeText={setStart} placeholder="Bắt đầu YYYY-MM-DD"/><TextInput style={[s.input,s.half]} value={end} onChangeText={setEnd} placeholder="Kết thúc"/></View>
 <View style={s.segment}><Pressable style={[s.seg,status==='active'&&s.segOn]} onPress={()=>setStatus('active')}><Text style={[s.segText,status==='active'&&s.segTextOn]}>Đang dùng</Text></Pressable><Pressable style={[s.seg,status==='stopped'&&s.segOn]} onPress={()=>setStatus('stopped')}><Text style={[s.segText,status==='stopped'&&s.segTextOn]}>Đã ngưng</Text></Pressable></View>
 <TextInput style={[s.input,s.multi]} value={sideEffects} onChangeText={setSideEffects} placeholder="Tác dụng phụ ghi nhận" multiline/><TextInput style={[s.input,s.multi]} value={notes} onChangeText={setNotes} placeholder="Ghi chú" multiline/><Pressable style={s.primary} onPress={save}><Text style={s.primaryText}>{id?'Lưu thay đổi':'Lưu thuốc'}</Text></Pressable>{id&&<Pressable onPress={reset}><Text style={s.cancel}>Hủy chỉnh sửa</Text></Pressable>}
 <Text style={s.heading}>Danh sách thuốc</Text>{items.length===0?<Text style={s.empty}>Chưa có thuốc nào.</Text>:items.map(x=><Pressable key={x.id} style={s.card} onPress={()=>edit(x)} onLongPress={()=>remove(x)}><View style={s.cardTop}><Text style={s.title}>{x.name}</Text><Text style={[s.badge,x.status==='stopped'&&s.badgeOff]}>{x.status==='active'?'ĐANG DÙNG':'ĐÃ NGƯNG'}</Text></View><Text style={s.details}>{[x.dosage,x.frequency].filter(Boolean).join(' · ')||'Chưa nhập liều/lịch'}</Text>{x.side_effects&&<Text style={s.side}>Tác dụng phụ: {x.side_effects}</Text>}</Pressable>)}</ScrollView>;
}
const baseStyles = StyleSheet.create({container:{padding:18,paddingBottom:50,gap:10,backgroundColor:'#F8FAFC'},hero:{backgroundColor:'#0F172A',borderRadius:22,padding:20},overline:{color:'#6EE7B7',fontSize:10,fontWeight:'900',letterSpacing:1},heroTitle:{color:'#fff',fontSize:24,fontWeight:'900',marginTop:5},heroText:{color:'#CBD5E1',fontSize:12,marginTop:6},heading:{fontSize:18,fontWeight:'900',color:'#0F172A',marginTop:8},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#D0D5DD',borderRadius:13,padding:12,color:'#0F172A'},row:{flexDirection:'row',gap:8},half:{flex:1},multi:{height:72,textAlignVertical:'top'},segment:{flexDirection:'row',backgroundColor:'#E2E8F0',padding:4,borderRadius:14},seg:{flex:1,padding:10,alignItems:'center',borderRadius:11},segOn:{backgroundColor:'#fff'},segText:{color:'#64748B',fontWeight:'800'},segTextOn:{color:'#0F172A'},primary:{backgroundColor:'#2563EB',padding:14,borderRadius:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},cancel:{textAlign:'center',color:'#64748B',fontWeight:'800'},empty:{backgroundColor:'#fff',padding:22,borderRadius:16,color:'#64748B',textAlign:'center'},card:{backgroundColor:'#fff',padding:14,borderRadius:16,borderWidth:1,borderColor:'#E2E8F0'},cardTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:15,fontWeight:'900',color:'#0F172A'},badge:{color:'#047857',fontSize:9,fontWeight:'900',backgroundColor:'#D1FAE5',padding:5,borderRadius:99},badgeOff:{color:'#64748B',backgroundColor:'#E2E8F0'},details:{color:'#475569',fontSize:12,marginTop:6},side:{color:'#B45309',fontSize:11,marginTop:6}});
