import { useThemedStyles } from "@/hooks/useTheme";
import { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { getTimeline } from '@/database/repositories/metricRepository';
import { getPatient } from '@/database/repositories/patientRepository';
import type { Patient } from '@/types/health';
import { buildHealthInsights, type HealthInsight } from '@/utils/healthInsights';

export default function InsightsScreen(){
  const s = useThemedStyles(baseStyles);const{patientId:raw}=useLocalSearchParams<{patientId:string}>();const id=Number(raw);const db=useSQLiteContext();const[patient,setPatient]=useState<Patient|null>(null);const[items,setItems]=useState<HealthInsight[]>([]);useFocusEffect(useCallback(()=>{Promise.all([getPatient(db,id),getTimeline(db,id,1000)]).then(([p,m])=>{setPatient(p);setItems(buildHealthInsights(m));});},[db,id]));return <ScrollView contentContainerStyle={s.container}><View style={s.hero}><Text style={s.overline}>HEALTH INSIGHTS</Text><Text style={s.title}>{patient?.name??'Phân tích sức khỏe'}</Text><Text style={s.sub}>Quy tắc chạy offline từ lịch sử và khoảng tham chiếu đã lưu.</Text></View>{items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>Chưa đủ dữ liệu</Text><Text style={s.emptyText}>Cần ít nhất một chỉ số để tạo nhận xét.</Text></View>:items.map(x=><View key={x.key} style={[s.card,x.tone==='warning'&&s.warn,x.tone==='positive'&&s.good]}><Text style={s.cardTitle}>{x.title}</Text><Text style={s.detail}>{x.detail}</Text></View>)}<Text style={s.notice}>Insights chỉ giúp nhận biết thay đổi trong dữ liệu, không phải chẩn đoán hay khuyến nghị điều trị.</Text></ScrollView>}
const baseStyles = StyleSheet.create({container:{padding:18,paddingBottom:50,gap:11,backgroundColor:'#F8FAFC'},hero:{backgroundColor:'#0F172A',padding:21,borderRadius:22},overline:{color:'#FDE68A',fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:'#fff',fontSize:24,fontWeight:'900',marginTop:5},sub:{color:'#CBD5E1',fontSize:12,marginTop:6},card:{backgroundColor:'#EFF6FF',borderColor:'#BFDBFE',borderWidth:1,borderRadius:16,padding:15},warn:{backgroundColor:'#FFF7ED',borderColor:'#FED7AA'},good:{backgroundColor:'#ECFDF5',borderColor:'#A7F3D0'},cardTitle:{color:'#0F172A',fontSize:14,fontWeight:'900'},detail:{color:'#64748B',fontSize:11,marginTop:5},empty:{backgroundColor:'#fff',padding:24,borderRadius:18,alignItems:'center'},emptyTitle:{fontWeight:'900',fontSize:16},emptyText:{color:'#64748B',marginTop:5},notice:{color:'#94A3B8',fontSize:10,lineHeight:15,textAlign:'center',marginTop:8}});
