import { useThemedStyles } from "@/hooks/useTheme";
import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { Stack, useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import DateTimeField from '@/components/form/DateTimeField';
import { getSelectedPatientId } from '@/database/repositories/patientRepository';
import { createReminder, deleteReminder, listReminders, REMINDER_KINDS, setReminderEnabled } from '@/database/repositories/reminderRepository';
import type { HealthReminder, ReminderKind, RepeatRule } from '@/types/health';
import { formatDateTime } from '@/utils/format';
import { cancelHealthReminder, scheduleHealthReminder, scheduleSavedReminder } from '@/utils/notifications';

const repeats:{key:RepeatRule;name:string;hint:string}[]=[
  {key:'none',name:'Một lần',hint:'Chỉ nhắc đúng thời điểm đã chọn'},
  {key:'daily',name:'Hằng ngày',hint:'Lặp lại mỗi ngày cùng giờ'},
  {key:'weekly',name:'Hằng tuần',hint:'Lặp lại cùng thứ và giờ'},
  {key:'monthly',name:'Hằng tháng',hint:'Lặp lại cùng ngày trong tháng'},
];

export default function RemindersScreen(){
  const s = useThemedStyles(baseStyles);
 const db=useSQLiteContext();const [patientId,setPatientId]=useState<number|null>(null);const [items,setItems]=useState<HealthReminder[]>([]);
 const [kind,setKind]=useState<ReminderKind>('medication');const [title,setTitle]=useState('');const [notes,setNotes]=useState('');const [date,setDate]=useState(()=>new Date(Date.now()+3600000));const [repeat,setRepeat]=useState<RepeatRule>('none');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const id=await getSelectedPatientId(db);setPatientId(id);setItems(id?await listReminders(db,id):[]);},[db]);useFocusEffect(useCallback(()=>{load();},[load]));
 async function add(){if(!patientId)return Alert.alert('Chưa có bệnh nhân','Hãy tạo hoặc chọn bệnh nhân trước.');if(!title.trim())return Alert.alert('Thiếu tiêu đề','Nhập nội dung cần nhắc.');setBusy(true);try{const notificationId=await scheduleHealthReminder({title:title.trim(),notes,patientId,scheduledAt:date.toISOString(),repeatRule:repeat});await createReminder(db,{patientId,kind,title,notes,scheduledAt:date.toISOString(),repeatRule:repeat,notificationId});setTitle('');setNotes('');await load();}catch(error){Alert.alert('Không thể tạo lời nhắc',error instanceof Error?error.message:'Đã xảy ra lỗi.');}finally{setBusy(false);}}
 async function toggle(item:HealthReminder,value:boolean){try{await cancelHealthReminder(item.notification_id);const id=value?await scheduleSavedReminder(item):null;await setReminderEnabled(db,item.id,value,id);await load();}catch(error){Alert.alert('Không thể cập nhật',error instanceof Error?error.message:'Đã xảy ra lỗi.');}}
 function remove(item:HealthReminder){Alert.alert('Xóa lời nhắc?',item.title,[{text:'Hủy',style:'cancel'},{text:'Xóa',style:'destructive',onPress:async()=>{await cancelHealthReminder(item.notification_id);await deleteReminder(db,item.id);await load();}}]);}
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Stack.Screen options={{title:'Nhắc lịch sức khỏe'}}/><View style={s.hero}><Text style={s.eyebrow}>SPRINT 11 · OFFLINE</Text><Text style={s.h1}>Đúng việc, đúng giờ</Text><Text style={s.sub}>Thông báo được hẹn ngay trên thiết bị cho thuốc, chỉ số và lịch khám. Quyền thông báo chỉ được hỏi khi bạn tạo lời nhắc đầu tiên.</Text></View>
 <Text style={s.label}>LOẠI NHẮC</Text><View style={s.chips}>{REMINDER_KINDS.map(x=><Pressable key={x.key} onPress={()=>setKind(x.key)} style={[s.chip,kind===x.key&&s.active]}><Text style={[s.chipText,kind===x.key&&s.activeText]}>{x.name}</Text></Pressable>)}</View>
 <TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Ví dụ: Uống Metformin"/><TextInput style={[s.input,s.notes]} value={notes} onChangeText={setNotes} placeholder="Ghi chú (không bắt buộc)" multiline/><DateTimeField value={date} onChange={setDate}/>
 <Text style={s.label}>CHU KỲ</Text><View style={s.grid}>{repeats.map(x=><Pressable key={x.key} onPress={()=>setRepeat(x.key)} style={[s.repeat,repeat===x.key&&s.active]}><Text style={[s.repeatName,repeat===x.key&&s.activeText]}>{x.name}</Text><Text style={[s.hint,repeat===x.key&&s.activeHint]}>{x.hint}</Text></Pressable>)}</View><Pressable style={[s.primary,busy&&s.disabled]} disabled={busy} onPress={add}><Text style={s.primaryText}>{busy?'Đang tạo…':'Tạo lời nhắc'}</Text></Pressable>
 <Text style={s.section}>Lời nhắc đã lưu</Text>{items.length===0?<Text style={s.empty}>Chưa có lời nhắc cho bệnh nhân đang chọn.</Text>:items.map(item=><Pressable key={item.id} style={s.card} onLongPress={()=>remove(item)}><View style={s.cardBody}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.meta}>{REMINDER_KINDS.find(x=>x.key===item.kind)?.name} · {formatDateTime(item.scheduled_at)}</Text><Text style={s.meta}>{repeats.find(x=>x.key===item.repeat_rule)?.name} · Giữ để xóa</Text></View><Switch value={!!item.enabled} onValueChange={v=>toggle(item,v)} trackColor={{true:'#93C5FD'}}/></Pressable>)}</ScrollView>;
}
const baseStyles = StyleSheet.create({page:{padding:18,paddingBottom:48,backgroundColor:'#F8FAFC',gap:12},hero:{backgroundColor:'#0F172A',borderRadius:24,padding:22},eyebrow:{color:'#93C5FD',fontWeight:'900',fontSize:11,letterSpacing:1},h1:{color:'white',fontSize:27,fontWeight:'900',marginTop:6},sub:{color:'#CBD5E1',lineHeight:20,marginTop:7},label:{fontSize:11,fontWeight:'900',color:'#64748B',marginTop:5},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:99,backgroundColor:'white',borderWidth:1,borderColor:'#E2E8F0'},active:{backgroundColor:'#2563EB',borderColor:'#2563EB'},chipText:{fontWeight:'800',color:'#475569'},activeText:{color:'white'},input:{backgroundColor:'white',borderWidth:1,borderColor:'#E2E8F0',borderRadius:15,padding:14,fontSize:15},notes:{minHeight:70,textAlignVertical:'top'},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},repeat:{width:'48%',padding:12,borderRadius:15,backgroundColor:'white',borderWidth:1,borderColor:'#E2E8F0'},repeatName:{fontWeight:'900',color:'#0F172A'},hint:{fontSize:11,color:'#64748B',marginTop:3,lineHeight:15},activeHint:{color:'#DBEAFE'},primary:{backgroundColor:'#2563EB',padding:16,borderRadius:16,alignItems:'center'},primaryText:{color:'white',fontWeight:'900',fontSize:16},disabled:{opacity:.55},section:{fontWeight:'900',fontSize:19,color:'#0F172A',marginTop:10},empty:{color:'#64748B',paddingVertical:18,textAlign:'center'},card:{backgroundColor:'white',borderWidth:1,borderColor:'#E2E8F0',borderRadius:17,padding:15,flexDirection:'row',alignItems:'center'},cardBody:{flex:1,paddingRight:10},cardTitle:{fontWeight:'900',fontSize:16,color:'#0F172A'},meta:{color:'#64748B',fontSize:12,marginTop:4}});
