import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { listClinicalEntries } from '@/database/repositories/clinicalRepository';
import { listMedications } from '@/database/repositories/medicationRepository';
import { getTimeline } from '@/database/repositories/metricRepository';
import { getPatient } from '@/database/repositories/patientRepository';
import type { ClinicalEntry, Medication, MetricPoint, Patient } from '@/types/health';
import { exportReportCsv, exportReportPdf, exportReportZip, type HealthReportData } from '@/utils/reportExport';
import AppIcon from '@/components/AppIcon';

export default function ReportsScreen(){const{patientId:raw}=useLocalSearchParams<{patientId:string}>();const id=Number(raw);const db=useSQLiteContext();const[months,setMonths]=useState(3);const[patient,setPatient]=useState<Patient|null>(null);const[metrics,setMetrics]=useState<MetricPoint[]>([]);const[clinical,setClinical]=useState<ClinicalEntry[]>([]);const[meds,setMeds]=useState<Medication[]>([]);const[busy,setBusy]=useState('');const load=useCallback(async()=>{const[p,m,c,md]=await Promise.all([getPatient(db,id),getTimeline(db,id,5000),listClinicalEntries(db,id),listMedications(db,id)]);setPatient(p);setMetrics(m);setClinical(c);setMeds(md);},[db,id]);useFocusEffect(useCallback(()=>{load();},[load]));const filtered=useMemo(()=>{const from=new Date();from.setMonth(from.getMonth()-months);return metrics.filter(x=>new Date(x.measured_at)>=from);},[metrics,months]);const data:HealthReportData|null=patient?{patient,metrics:filtered,clinical,medications:meds,months}:null;async function run(kind:'pdf'|'csv'|'zip'){if(!data)return;setBusy(kind);try{if(kind==='pdf')await exportReportPdf(data);else if(kind==='csv')await exportReportCsv(data);else await exportReportZip(data);}catch(e){Alert.alert('Không thể xuất báo cáo',e instanceof Error?e.message:'Đã xảy ra lỗi.');}finally{setBusy('');}}
 return <ScrollView contentContainerStyle={s.container}><View style={s.hero}><Text style={s.overline}>BÁO CÁO SỨC KHỎE</Text><Text style={s.title}>{patient?.name??'Đang tải…'}</Text><Text style={s.sub}>Tổng hợp chỉ số, thuốc và lịch sử khám để xem hoặc chia sẻ cho bác sĩ.</Text></View><View style={s.periods}>{[1,3,6,12].map(x=><Pressable key={x} style={[s.period,months===x&&s.periodOn]} onPress={()=>setMonths(x)}><Text style={[s.periodText,months===x&&s.periodTextOn]}>{x} tháng</Text></Pressable>)}</View><View style={s.summary}><View><Text style={s.big}>{filtered.length}</Text><Text style={s.label}>CHỈ SỐ TRONG KỲ</Text></View><View><Text style={s.big}>{clinical.length}</Text><Text style={s.label}>MỤC BỆNH ÁN</Text></View><View><Text style={s.big}>{meds.filter(x=>x.status==='active').length}</Text><Text style={s.label}>THUỐC ĐANG DÙNG</Text></View></View><Text style={s.heading}>Xuất và chia sẻ</Text><Text style={s.help}>PDF phù hợp để đọc/in; CSV dùng cho bảng tính; ZIP chứa cả PDF và CSV.</Text>{(['pdf','csv','zip'] as const).map(kind=><Pressable key={kind} style={s.action} onPress={()=>run(kind)} disabled={!!busy}>{busy===kind?<ActivityIndicator color="#2563EB"/>:<><Text style={s.actionTitle}>{kind==='pdf'?'Báo cáo PDF':kind==='csv'?'Dữ liệu CSV':'Gói hồ sơ ZIP'}</Text><AppIcon ios="chevron.right" android="chevron_right" size={17}/></>}</Pressable>)}<Text style={s.notice}>Chỉ chia sẻ dữ liệu y tế với người nhận và kênh bạn tin tưởng.</Text></ScrollView>}
const s=StyleSheet.create({container:{padding:18,paddingBottom:50,gap:11,backgroundColor:'#F8FAFC'},hero:{backgroundColor:'#0F172A',padding:21,borderRadius:22},overline:{color:'#93C5FD',fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:'#fff',fontSize:24,fontWeight:'900',marginTop:5},sub:{color:'#CBD5E1',fontSize:12,lineHeight:18,marginTop:6},periods:{flexDirection:'row',gap:7},period:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:'#E2E8F0',padding:10,borderRadius:12,alignItems:'center'},periodOn:{backgroundColor:'#2563EB',borderColor:'#2563EB'},periodText:{fontSize:11,color:'#64748B',fontWeight:'900'},periodTextOn:{color:'#fff'},summary:{backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:'#E2E8F0',padding:14,flexDirection:'row',justifyContent:'space-between'},big:{fontSize:22,fontWeight:'900',color:'#0F172A'},label:{fontSize:8,color:'#94A3B8',fontWeight:'900',marginTop:3},heading:{fontSize:18,fontWeight:'900',color:'#0F172A',marginTop:5},help:{color:'#64748B',fontSize:11},action:{minHeight:58,backgroundColor:'#fff',borderWidth:1,borderColor:'#DCE3EC',borderRadius:15,paddingHorizontal:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},actionTitle:{color:'#0F172A',fontWeight:'900'},notice:{color:'#B45309',backgroundColor:'#FFFBEB',padding:12,borderRadius:12,fontSize:10,textAlign:'center'}});
