import { useCallback, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { SafeAreaView } from 'react-native-safe-area-context';
import EmptyState from '@/components/EmptyState';
import { getPatient, getSelectedPatientId } from '@/database/repositories/patientRepository';
import { getTimeline } from '@/database/repositories/metricRepository';
import type { MetricPoint, MetricSource, Patient } from '@/types/health';
import { formatDate, formatMetricValue, formatTime } from '@/utils/format';
import AppIcon from '@/components/AppIcon';
type Filter='all'|MetricSource;
export default function TimelineScreen(){
 const db=useSQLiteContext();const[patient,setPatient]=useState<Patient|null>(null);const[items,setItems]=useState<MetricPoint[]>([]);const[filter,setFilter]=useState<Filter>('all');
 const load=useCallback(async()=>{const id=await getSelectedPatientId(db);if(!id){setPatient(null);setItems([]);return;}setPatient(await getPatient(db,id));setItems(await getTimeline(db,id,300,'all'));},[db]);useFocusEffect(useCallback(()=>{load();},[load]));
 const visible=useMemo(()=>filter==='all'?items:items.filter(x=>x.source===filter),[items,filter]);
 const groups=useMemo(()=>{const map=new Map<string,MetricPoint[]>();for(const x of visible){const d=new Date(x.measured_at);const key=`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;map.set(key,[...(map.get(key)??[]),x]);}return [...map.values()];},[visible]);
 return <SafeAreaView style={styles.safeArea} edges={['top','left','right']}><ScrollView contentContainerStyle={[styles.container,{paddingBottom:130}]}>
  <View style={styles.header}><View><Text style={styles.label}>HEALTH HISTORY</Text><Text style={styles.title}>{patient?.name||'Timeline'}</Text></View>{patient&&<Pressable style={styles.addBtn} onPress={()=>router.push({pathname:'/records/new',params:{patientId:patient.id}})}><AppIcon ios="plus" android="add" size={21} color="#FFFFFF"/></Pressable>}</View>
  <View style={styles.filters}>{([['all','Tất cả'],['vital','Sinh hiệu'],['lab','Xét nghiệm']] as const).map(([k,t])=><Pressable key={k} style={[styles.filter,filter===k&&styles.filterActive]} onPress={()=>setFilter(k)}><Text style={[styles.filterText,filter===k&&styles.filterTextActive]}>{t}</Text></Pressable>)}</View>
  {!patient?<EmptyState title="Chưa có bệnh nhân" text="Tạo và chọn một bệnh nhân trước."/>:visible.length===0?<EmptyState title="Chưa có lịch sử" text="Không có dữ liệu trong nhóm đang chọn."/>:groups.map((group,gi)=><View key={gi} style={styles.group}><Text style={styles.dateHeader}>{formatDate(group[0].measured_at)}</Text>{group.map(item=><Pressable key={`${item.source}-${item.id}`} style={styles.row} onPress={()=>router.push({pathname:'/records/[source]/[id]',params:{source:item.source,id:item.id}})}><View style={[styles.dot,item.source==='lab'&&styles.labDot]}><Text style={styles.dotText}>{item.source==='lab'?'L':'V'}</Text></View><View style={styles.info}><Text style={styles.name}>{item.metric_name}</Text><Text style={styles.meta}>{formatTime(item.measured_at)}{item.notes?`  ·  ${item.notes}`:''}</Text></View><View style={styles.right}><Text style={styles.value}>{formatMetricValue(item.value,item.value2)}</Text><Text style={styles.unit}>{item.unit}  ›</Text></View></Pressable>)}</View>)}
  {visible.length>0&&<Text style={styles.tip}>Chạm vào một dòng để sửa hoặc xóa dữ liệu.</Text>}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:'#F8FAFC'},container:{padding:18,paddingBottom:44,gap:12,backgroundColor:'#F8FAFC',minHeight:'100%'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},label:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#64748B'},title:{fontSize:25,fontWeight:'900',color:'#0F172A',marginTop:2},addBtn:{width:42,height:42,borderRadius:14,backgroundColor:'#2563EB',alignItems:'center',justifyContent:'center'},filters:{flexDirection:'row',gap:8,marginVertical:4},filter:{paddingHorizontal:14,paddingVertical:9,borderRadius:99,backgroundColor:'#fff',borderWidth:1,borderColor:'#E2E8F0'},filterActive:{backgroundColor:'#0F172A',borderColor:'#0F172A'},filterText:{fontSize:12,fontWeight:'900',color:'#64748B'},filterTextActive:{color:'#fff'},group:{gap:8,marginTop:4},dateHeader:{fontSize:12,fontWeight:'900',color:'#64748B',textTransform:'capitalize',marginTop:5},row:{backgroundColor:'#fff',borderRadius:17,padding:14,flexDirection:'row',alignItems:'center',gap:11,borderWidth:1,borderColor:'#E2E8F0'},dot:{width:34,height:34,borderRadius:11,backgroundColor:'#EFF6FF',alignItems:'center',justifyContent:'center'},labDot:{backgroundColor:'#ECFDF5'},dotText:{fontSize:11,fontWeight:'900',color:'#2563EB'},info:{flex:1},name:{fontSize:14,fontWeight:'900',color:'#0F172A'},meta:{fontSize:10,color:'#94A3B8',marginTop:4,maxWidth:180},right:{alignItems:'flex-end'},value:{fontSize:16,fontWeight:'900',color:'#0F172A'},unit:{fontSize:10,color:'#94A3B8',marginTop:3,fontWeight:'700'},tip:{fontSize:11,color:'#94A3B8',textAlign:'center',marginTop:10}});
