import { Directory, File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import type { SQLiteDatabase } from 'expo-sqlite';
import { decryptWithPassword, encryptWithPassword } from '@/utils/encryption';
import { locateStoredDocument, materializeDocument, protectStoredDocument } from '@/utils/protectedFile';
import { cancelAllHealthReminders, scheduleSavedReminder } from '@/utils/notifications';
import type { HealthReminder } from '@/types/health';

const tableOrder=['patients','documents','lab_results','vital_signs','medications','clinical_entries','reminders','app_settings'] as const;
const allowed:Record<(typeof tableOrder)[number],string[]>={patients:['id','name','dob','gender','blood_type','notes','created_at','updated_at'],documents:['id','patient_id','type','file_name','file_path','ocr_text','document_date','category','hospital','doctor','notes','created_at','updated_at'],lab_results:['id','patient_id','document_id','test_code','test_name','value','unit','reference_min','reference_max','reference_text','tested_at','notes','source_line','created_at'],vital_signs:['id','patient_id','type','value1','value2','unit','measured_at','notes','created_at'],medications:['id','patient_id','name','dosage','frequency','start_date','end_date','status','side_effects','notes','created_at','updated_at'],clinical_entries:['id','patient_id','document_id','kind','title','content','interpretation','symptoms','details','event_date','facility','clinician','created_at','updated_at'],reminders:['id','patient_id','kind','title','notes','scheduled_at','repeat_rule','notification_id','enabled','created_at','updated_at'],app_settings:['key','value']};
type BackupPayload={version:1;createdAt:string;tables:Record<string,Record<string,unknown>[]>;files:{documentId:number;name:string;base64:string}[]};
type PlainBackupEnvelope={format:'health-tracker-backup-plain';version:1;payload:BackupPayload};

async function collectBackup(db:SQLiteDatabase){const tables:BackupPayload['tables']={};for(const table of tableOrder)tables[table]=await db.getAllAsync(`SELECT * FROM ${table}`);const files:BackupPayload['files']=[];for(const row of tables.documents??[]){const source=locateStoredDocument(String(row.file_path));if(source.exists){const uri=await materializeDocument(source.uri,String(row.file_name||source.name));files.push({documentId:Number(row.id),name:String(row.file_name||source.name),base64:await new File(uri).base64()});}}return {version:1 as const,createdAt:new Date().toISOString(),tables,files};}

export async function createBackup(db:SQLiteDatabase,password?:string){const payload=await collectBackup(db);const content=password?await encryptWithPassword(JSON.stringify(payload),password):JSON.stringify({format:'health-tracker-backup-plain',version:1,payload} satisfies PlainBackupEnvelope);const suffix=password?'healthbackup':'healthbackup.json';const output=new File(Paths.cache,`health-tracker-backup-${new Date().toISOString().slice(0,10)}.${suffix}`);output.create({overwrite:true});output.write(content);if(!(await Sharing.isAvailableAsync()))throw new Error('Thiết bị không hỗ trợ bảng chia sẻ.');await Sharing.shareAsync(output.uri,{mimeType:'application/octet-stream',dialogTitle:'Lưu backup Health Tracker'});return output.uri;}

export async function createEncryptedBackup(db:SQLiteDatabase,password:string){return createBackup(db,password);}

export async function pickAndRestoreBackup(db:SQLiteDatabase,password?:string){const picked=await File.pickFileAsync({mimeTypes:['application/octet-stream','application/json','*/*']});if(picked.canceled)return false;const raw=await picked.result.text();let parsed:BackupPayload;const envelope=JSON.parse(raw) as Partial<PlainBackupEnvelope>;if(envelope.format==='health-tracker-backup-plain'&&envelope.payload){parsed=envelope.payload;}else{if(!password)throw new Error('Backup này có mật khẩu. Hãy nhập mật khẩu để khôi phục.');parsed=JSON.parse(await decryptWithPassword(raw,password)) as BackupPayload;}const payload=parsed;if(payload.version!==1||!payload.tables)throw new Error('Backup không tương thích.');const directory=new Directory(Paths.document,'medical-documents');if(!directory.exists)directory.create({intermediates:true});const paths=new Map<number,string>();for(const saved of payload.files??[]){const target=new File(directory,`restored-${saved.documentId}-${saved.name}`);target.create({overwrite:true,intermediates:true});target.write(saved.base64,{encoding:'base64'});await protectStoredDocument(target.uri);paths.set(saved.documentId,target.uri);}for(const row of payload.tables.documents??[]){const restored=paths.get(Number(row.id));if(restored)row.file_path=restored;}
 await cancelAllHealthReminders();await db.withExclusiveTransactionAsync(async txn=>{for(const table of [...tableOrder].reverse())await txn.execAsync(`DELETE FROM ${table}`);for(const table of tableOrder){for(const row of payload.tables[table]??[]){if(table==='reminders')row.notification_id=null;const columns=allowed[table].filter(column=>Object.hasOwn(row,column));if(!columns.length)continue;const values=columns.map(column=>row[column] as any);await txn.runAsync(`INSERT INTO ${table} (${columns.join(',')}) VALUES (${columns.map(()=>'?').join(',')})`,...values);}}});
 const reminders=await db.getAllAsync<HealthReminder>('SELECT r.*, p.name AS patient_name FROM reminders r JOIN patients p ON p.id=r.patient_id WHERE r.enabled=1');for(const reminder of reminders){try{const notificationId=await scheduleSavedReminder(reminder);await db.runAsync('UPDATE reminders SET notification_id=? WHERE id=?',notificationId,reminder.id);}catch{await db.runAsync('UPDATE reminders SET enabled=0, notification_id=NULL WHERE id=?',reminder.id);}}return true;}
